added ollama tinyllama functionality and now returning answers to my questions

diff --git a/app/Dockerfile b/app/Dockerfile
--- a/app/Dockerfile
+++ b/app/Dockerfile
@@ -29,5 +29,19 @@ EXPOSE 5001
 ENV PYTHONDONTWRITEBYTECODE=1
 ENV PYTHONUNBUFFERED=1
 
+# 👇 Install certifi if not present and override it with system certs (Zscaler trusted)
+RUN python -m pip install certifi \
+    && CERT_PATH=$(python -m certifi) \
+    && ln -sf /etc/ssl/certs/ca-certificates.crt $CERT_PATH
+
+
+# 👇 Define an environment variable for model cache
+ENV SENTENCE_TRANSFORMERS_HOME=/root/.cache/torch/sentence_transformers
+#check the container has outbound network access during build
+RUN curl -I https://huggingface.co
+#pre-download sentence_transformer model inside the container during build
+RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')"
+RUN test -d /root/.cache/torch/sentence_transformers && echo "✅ Model cached successfully" || echo "❌ Model not found"
+
 # 🚀 Start app with Gunicorn
 CMD gunicorn --bind 0.0.0.0:${PORT:-5000} run:app
